### ISSUE TITLE
Unpinned mcp>=1.0 installs SDK 2.x and the MCP server fails to start

### ISSUE THREAD

**Issue by marcospaula** [ScottDuncanAI/industrial-ai-troubleshooting-agent#4]
## Summary

`requirements.txt` specifies `mcp>=1.0` with no upper bound. The MCP Python SDK released 2.0 after this repo's last commit, so a fresh `/setup` today installs **mcp 2.1.1**, where the low-level `Server` API changed. `historian_mcp_server.py` uses the 1.x form and dies on import, so none of the 23 tools ever register.

This is worth flagging above the usual dependency nit because of who it hits. The README says *"Claude will install everything automatically. No coding required."* A non-technical user runs `/setup`, waits through the download, restarts Claude Code, and the boiler tools simply are not there. The only clue is a Python traceback they have no way to act on.

## Reproduction

Fresh clone, fresh venv, `pip install -r requirements.txt`, then start the server:

```
$ .venv/bin/python historian_mcp_server.py
Traceback (most recent call last):
  File "historian_mcp_server.py", line 63, in <module>
    @server.list_tools()
     ^^^^^^^^^^^^^^^^^
AttributeError: 'Server' object has no attribute 'list_tools'
```

Line 63 is the decorator on `list_tools()`, immediately after `server = Server("boiler-historian")`.

## Fix

One line in `requirements.txt`:

```diff
-mcp>=1.0
+mcp>=1.0,<2
```

With `mcp 1.29.1` (latest 1.x) the server starts normally and a `tools/list` handshake returns all 23 tools. Verified end to end: `historian_get_data_range`, `historian_get_statistics`, `historian_get_tag_data`, `alarm_query` and `docs_search` all return correct results against the shipped databases.

If migrating to the 2.x API is on the roadmap, the cap is still the right thing to have in the meantime, since the committed code is 1.x.

## Note on how this stays invisible locally

An existing venv created before the 2.0 release keeps working, so the failure only shows up on a clean install. Nothing in the repo pins or records the working version, which is why it can pass unnoticed on the maintainer's machine while breaking for every new user.

## Environment

- OS: Fedora Linux, kernel 7.1.10
- Python: 3.14.7
- Resolved by `mcp>=1.0` today: 2.1.1 (broken) · works with 1.29.1
- Repo at commit `99cf4d0`

Related: #3 (the CUDA PyTorch build is pulled on machines with no NVIDIA GPU). Both are `requirements.txt` issues but independent; happy to send a single PR covering both if that is easier.
